config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"
  # get "tasks", to: "tasks#index"
  # get "tasks/new", to: "tasks#new", as: :new_task
  # get "tasks/:id", to: "tasks#show", as: :task_show
  # post "tasks", to: "tasks#create", as: :create_task
  # get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  # patch "tasks/:id", to: "tasks#update", as: :update_task
  # delete "tasks/:id", to: "tasks#destroy", as: :destroy_task
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_tasks, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path, notice: "Task Created!"
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to tasks_path(@task)
    else
      render 'edit'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def set_tasks
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/details.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
</div>
<%= link_to "Back to List", tasks_path %>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>EDIT TASK</h1>
  <%= form_with model: @task, url: task_path(@task), method: :patch do |task| %>
    <div class="form-group">
      <%= task.label :title %>
      <%= task.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= task.label :details %>
      <%= task.text_field :details, class: "form-control" %>
    </div>
    <div class="form-group form-check">
      <%= task.check_box :completed, class: "form-check-input", checked: @task.completed? %>
      <%= task.label :completed, class: "form-check-label" %>
    </div>
    <%= task.submit "Confirm Edit", class: "btn btn-primary" %>
    <%= link_to "Back to List", tasks_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul class="list-group py-3">
    <% @tasks.each do |task| %>
      <li class="list-group-item py-3">
        <div class="form-check">
          <% if task.completed %>
            <i class="fa-solid fa-circle-check"></i>
          <% else %>
            <i class="fa-regular fa-circle"></i>
          <% end %>
          <label class="form-check-label" for="task_<%= task.id %>">
            <%= link_to task.title, task_path(task) %>
          </label>
        </div>
      </li>
    <% end %>
  </ul>
  <%= link_to "Add a new task", new_task_path, class: "btn btn-primary" %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>New Task</h1>
  <%= form_with model: @task, url: tasks_path(@task), method: :post, class: "form" do |task| %>
    <div class="form-group">
      <%= task.label :title, class: "font-weight-bold" %>
      <%= task.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= task.label :details, class: "font-weight-bold" %>
      <%= task.text_field :details, class: "form-control" %>
    </div>
    <%= task.submit "Create Task", class: "btn btn-primary" %>
    <%= link_to "Back to List", tasks_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="card">
    <div class="card-body">
      <h1 class="card-title"><%= @task.title %></h1>
      <p class="card-text"><%= @task.details %></p>
      <strong class="card-text"><%= @task.completed ? "Completed" : "Task not completed" %></strong>
      <br>
      <%= link_to "Edit Task", edit_task_path(@task), class: "btn btn-primary mt-3" %>
      <%= link_to "Back to List", tasks_path, class: "btn btn-secondary mt-3" %>
      <%= link_to "Delete", task_path(@task), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger mt-3" %>
    </div>
  </div>
</div>